USE [master]
GO

/****** Object:  Database [TeleCommPortal]    Script Date: 7/11/2018 17:34:22 ******/
CREATE DATABASE [TeleCommPortal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TelCommPortal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TelCommPortal.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TelCommPortal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TelCommPortal_log.ldf' , SIZE = 15360KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TeleCommPortal] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TeleCommPortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TeleCommPortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TeleCommPortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TeleCommPortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TeleCommPortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TeleCommPortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [TeleCommPortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TeleCommPortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TeleCommPortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TeleCommPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TeleCommPortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TeleCommPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TeleCommPortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TeleCommPortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TeleCommPortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TeleCommPortal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TeleCommPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TeleCommPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TeleCommPortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TeleCommPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TeleCommPortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TeleCommPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TeleCommPortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TeleCommPortal] SET RECOVERY FULL 
GO

ALTER DATABASE [TeleCommPortal] SET  MULTI_USER 
GO

ALTER DATABASE [TeleCommPortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TeleCommPortal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TeleCommPortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TeleCommPortal] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TeleCommPortal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TeleCommPortal] SET QUERY_STORE = OFF
GO

USE [TeleCommPortal]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TeleCommPortal] SET  READ_WRITE 
GO

